version: '3.7'

services:
  db:
    image: postgres
    container_name: ${APP_NAME}-postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  adminer:
    image: adminer
    container_name: ${APP_NAME}-adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db-data:
